#! /bin/bash

diff  testsuite/25_algorithms/adjacent_find/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/adjacent_find/constexpr.cc
diff  testsuite/25_algorithms/all_of/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/all_of/constexpr.cc
diff  testsuite/25_algorithms/any_of/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/any_of/constexpr.cc
diff  testsuite/25_algorithms/binary_search/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/binary_search/constexpr.cc
diff  testsuite/25_algorithms/copy_backward/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/copy_backward/constexpr.cc
diff  testsuite/25_algorithms/copy/constexpr.cc				../gcc_git/libstdc++-v3/testsuite/25_algorithms/copy/constexpr.cc
diff  testsuite/25_algorithms/copy_if/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/copy_if/constexpr.cc
diff  testsuite/25_algorithms/copy_n/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/copy_n/constexpr.cc
diff  testsuite/25_algorithms/count/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/count/constexpr.cc
diff  testsuite/25_algorithms/count_if/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/count_if/constexpr.cc
diff  testsuite/25_algorithms/equal/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/equal/constexpr.cc
diff  testsuite/25_algorithms/equal_range/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/equal_range/constexpr.cc
diff  testsuite/25_algorithms/fill/constexpr.cc				../gcc_git/libstdc++-v3/testsuite/25_algorithms/fill/constexpr.cc
diff  testsuite/25_algorithms/fill_n/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/fill_n/constexpr.cc
diff  testsuite/25_algorithms/find/constexpr.cc				../gcc_git/libstdc++-v3/testsuite/25_algorithms/find/constexpr.cc
diff  testsuite/25_algorithms/find_end/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/find_end/constexpr.cc
diff  testsuite/25_algorithms/find_first_of/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/find_first_of/constexpr.cc
diff  testsuite/25_algorithms/find_if/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/find_if/constexpr.cc
diff  testsuite/25_algorithms/find_if_not/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/find_if_not/constexpr.cc
diff  testsuite/25_algorithms/for_each/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/for_each/constexpr.cc
diff  testsuite/25_algorithms/generate/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/generate/constexpr.cc
diff  testsuite/25_algorithms/generate_n/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/generate_n/constexpr.cc
diff  testsuite/25_algorithms/is_heap/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/is_heap/constexpr.cc
diff  testsuite/25_algorithms/is_heap_until/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/is_heap_until/constexpr.cc
diff  testsuite/25_algorithms/is_partitioned/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/is_partitioned/constexpr.cc
diff  testsuite/25_algorithms/is_permutation/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/is_permutation/constexpr.cc
diff  testsuite/25_algorithms/is_sorted/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/is_sorted/constexpr.cc
diff  testsuite/25_algorithms/is_sorted_until/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/is_sorted_until/constexpr.cc
diff  testsuite/25_algorithms/lexicographical_compare/constexpr.cc	../gcc_git/libstdc++-v3/testsuite/25_algorithms/lexicographical_compare/constexpr.cc
diff  testsuite/25_algorithms/lower_bound/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/lower_bound/constexpr.cc
diff  testsuite/25_algorithms/merge/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/merge/constexpr.cc
diff  testsuite/25_algorithms/mismatch/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/mismatch/constexpr.cc
diff  testsuite/25_algorithms/none_of/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/none_of/constexpr.cc
diff  testsuite/25_algorithms/partition_copy/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/partition_copy/constexpr.cc
diff  testsuite/25_algorithms/partition_point/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/partition_point/constexpr.cc
diff  testsuite/25_algorithms/remove/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/remove/constexpr.cc
diff  testsuite/25_algorithms/remove_copy/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/remove_copy/constexpr.cc
diff  testsuite/25_algorithms/remove_copy_if/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/remove_copy_if/constexpr.cc
diff  testsuite/25_algorithms/remove_if/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/remove_if/constexpr.cc
diff  testsuite/25_algorithms/replace_copy/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/replace_copy/constexpr.cc
diff  testsuite/25_algorithms/replace_copy_if/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/replace_copy_if/constexpr.cc
diff  testsuite/25_algorithms/replace_if/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/replace_if/constexpr.cc
diff  testsuite/25_algorithms/reverse_copy/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/reverse_copy/constexpr.cc
diff  testsuite/25_algorithms/rotate_copy/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/rotate_copy/constexpr.cc
diff  testsuite/25_algorithms/search/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/search/constexpr.cc
diff  testsuite/25_algorithms/search_n/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/search_n/constexpr.cc
diff  testsuite/25_algorithms/set_difference/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/set_difference/constexpr.cc
diff  testsuite/25_algorithms/set_intersection/constexpr.cc		../gcc_git/libstdc++-v3/testsuite/25_algorithms/set_intersection/constexpr.cc
diff  testsuite/25_algorithms/set_symmetric_difference/constexpr.cc	../gcc_git/libstdc++-v3/testsuite/25_algorithms/set_symmetric_difference/constexpr.cc
diff  testsuite/25_algorithms/set_union/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/set_union/constexpr.cc
diff  testsuite/25_algorithms/transform/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/transform/constexpr.cc
diff  testsuite/25_algorithms/unique/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/unique/constexpr.cc
diff  testsuite/25_algorithms/unique_copy/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/unique_copy/constexpr.cc
diff  testsuite/25_algorithms/upper_bound/constexpr.cc			../gcc_git/libstdc++-v3/testsuite/25_algorithms/upper_bound/constexpr.cc
